### ISSUE TITLE
Wrong email in the form

### ISSUE THREAD

**Issue by end3r** [jubelcassio/js13kGames-Entry#1]
Hey, can you get in touch with me? The email you entered in the form when submitting your js13kGames entry seems wrong as all the messages are bouncing off. I have a t-shirt to ship (for System Crawler placing 37th), but no way of contacing you to ask for the details.

**Comment by end3r** [comment]
The one from here: https://github.com/jubelcassio/jubelcassio.github.io/blob/master/_config.yml is also the same in the form. Are you sure it's correct?

**Comment by jubelcassio** [comment]
Hello, thanks for contacting me.
The email is not correct, must've filled it wrong by force of habit, since it is the same as an old address I used to have. I apologize for my mistake and any inconvenience it may have caused.
The correct email is: jubelcassioverridasilva@gmail.com, I set it up to public on my GitHub profile.

**Comment by end3r** [comment]
Cool, I've forwarded you the last email with the link to the form.
